const Contents = {
  'stripe-reports-insights': {
    id: 'stripe-reports-insights',
    number: 0,
    title: 'Insights from our first project reports',
    section: 'research',
    tags: ['note', 'commentary'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '05-18-2020',
    color: 'yellow',
    background: 'road.png',
    icon: 'road-small.png',
  },
  'soil-carbon-comment': {
    id: 'soil-carbon-comment',
    number: 1,
    title: 'Getting soil carbon right',
    section: 'research',
    tags: ['note', 'commentary'],
    authors: ['Danny Cullenward', 'Jeremy Freeman'],
    version: '1.0.0',
    date: '06-01-2020',
    color: 'orange',
    background: 'article-001/soil.png',
    icon: 'article-001/soil-small.png',
  },
  'forest-climate-risks': {
    id: 'forest-climate-risks',
    number: 2,
    title: 'Climate-driven risks to forest carbon',
    section: 'research',
    tags: ['publication'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '06-23-2020',
    color: 'green',
    background: 'article-002/tree.png',
    icon: 'article-002/tree-small.png',
  },
}

export default Contents
