const Contents = {
  'stripe-reports-insights': {
    title: 'Insights from our first project reports',
    tags: ['note', 'commentary'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '05-18-2020',
    color: 'yellow',
    icon: 'road-small.png',
  },
  'soil-carbon-comment': {
    title: 'Getting soil carbon right',
    tags: ['comment'],
    authors: ['Danny Cullenward', 'Jeremy Freeman'],
    version: '1.0.0',
    date: '06-01-2020',
    color: 'orange',
    icon: 'article-001/soil-small.png',
  },
  'forest-climate-risks': {
    title: 'Climate-driven risks to forest carbon',
    tags: ['publication'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '06-23-2020',
    color: 'green',
    icon: 'article-002/tree-small.png',
  },
  'carbon-removal-mechanisms': {
    title: 'Carbon removal mechanisms',
    tags: ['explainer'],
    authors: ['CarbonPlan Team', 'Toly Rinberg'],
    version: '1.0.0',
    date: '07-24-2020',
    color: 'grey',
    icon: 'article-003/pipes-small.png',
  },
  'offset-project-fire': {
    title: 'Carbon offsets burning',
    tags: ['note', 'analysis'],
    authors: [
      'Claudia Herbert',
      'Jared Stapp',
      'Grayson Badgley',
      'William R L Anderegg',
      'CarbonPlan Team',
    ],
    version: '1.0.0',
    date: '09-17-2020',
    color: 'red',
    icon: 'article-004/forest-small.png',
  },
  'permanence-calculator-explainer': {
    title: 'The cost of temporary carbon removal',
    tags: ['tool', 'explainer'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '12-09-2020',
    color: 'pink',
    icon: 'article-005/leaf-small.png',
  },
  'permanence-calculator': {
    title: 'Permanence calculator',
    tags: ['tool'],
    authors: ['CarbonPlan team'],
    version: '1.0.0',
    date: '12-09-2020',
    color: 'pink',
  },
}

export default Contents
