const Contents = {
  'stripe-reports-insights': {
    id: 'stripe-reports-insights',
    number: 0,
    title: 'Insights from our first project reports',
    section: 'research',
    tags: ['note', 'commentary'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '05-18-2020',
    color: 'yellow',
    background: 'road.png',
    icon: 'road-small.png',
  },
  'soil-carbon-comment': {
    id: 'soil-carbon-comment',
    number: 1,
    title: 'Getting soil carbon right',
    section: 'research',
    tags: ['note', 'commentary'],
    authors: ['Danny Cullenward', 'Jeremy Freeman'],
    version: '1.0.0',
    date: '06-01-2020',
    color: 'orange',
    background: 'article-001/soil.png',
    icon: 'article-001/soil-small.png',
  },
  'forest-climate-risks': {
    id: 'forest-climate-risks',
    number: 2,
    title: 'Climate-driven risks to forest carbon',
    section: 'research',
    tags: ['publication'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '06-23-2020',
    color: 'green',
    background: 'article-002/tree.png',
    icon: 'article-002/tree-small.png',
  },
  'carbon-removal-mechanisms': {
    id: 'carbon-removal-mechanisms',
    number: 3,
    title: 'Carbon removal mechanisms',
    section: 'research',
    tags: ['explainer'],
    authors: ['CarbonPlan Team', 'Toly Rinberg'],
    version: '1.0.0',
    date: '07-24-2020',
    color: 'grey',
    background: 'article-003/pipes.png',
    icon: 'article-003/pipes-small.png',
    invert: true,
  },
  'offset-project-fire': {
    id: 'offset-project-fire',
    number: 4,
    title: 'Carbon offsets burning',
    section: 'research',
    tags: ['note', 'analysis'],
    authors: [
      'Claudia Herbert',
      'Jared Stapp',
      'Grayson Badgley',
      'William R L Anderegg',
      'CarbonPlan Team',
    ],
    version: '1.0.0',
    date: '09-17-2020',
    color: 'red',
    background: 'article-004/forest.png',
    icon: 'article-004/forest-small.png',
    invert: true,
  },
  'permanence-calculator-explainer': {
    id: 'permanence-calculator-explainer',
    number: 5,
    title: 'The cost of temporary carbon removal',
    section: 'research',
    tags: ['tool', 'explainer'],
    authors: ['CarbonPlan Team'],
    version: '1.0.0',
    date: '12-09-2020',
    color: 'pink',
    background: 'article-005/leaf.png',
    icon: 'article-005/leaf-small.png',
    invert: true,
  },
  'permanence-calculator': {
    id: 'permanence-calculator',
    number: 0,
    title: 'Permanence calculator',
    section: 'research',
    tags: ['tool'],
    authors: ['CarbonPlan team'],
    version: '1.0.0',
    date: '12-09-2020',
    color: 'pink',
    hideTop: true,
  },
}

export default Contents
