import {
  ForestOffsetsCrediting,
  ForestOffsetsFires,
  ForestRisks,
  CDRDatabase,
  PermanenceCalculator,
  DACCalculator,
  SoilProtocols,
  ComplianceUsers,
  ForestCarbon,
  SeaweedFarming,
  CMIP6Downscaling,
  CDRVerification,
  EWQuantification,
  OffsetsDB,
  OAEEfficiency,
  DOREfficiency,
} from '../components/tool-logos'

const tools = [
  {
    id: 'dor-efficiency',
    logo: <DOREfficiency />,
    color: 'secondary',
    summary: 'Mapping the efficiency of direct ocean removal.',
    title: 'DOR Efficiency',
    date: '06-04-2025',
  },
  {
    id: 'oae-efficiency',
    logo: <OAEEfficiency />,
    color: 'secondary',
    summary: 'Mapping the efficiency of ocean alkalinity enhancement.',
    title: 'OAE Efficiency',
    date: '06-04-2025',
  },
  {
    id: 'offsets-db',
    logo: <OffsetsDB />,
    color: 'secondary',
    summary: 'A harmonized database of carbon offset projects and credits.',
    displayName: 'OFFSETS DB', // Use space when all-caps
    title: 'OffsetsDB',
    date: '04-23-2025',
  },
  {
    id: 'ew-quantification',
    logo: <EWQuantification />,
    color: 'secondary',
    summary:
      'A tool for exploring different quantitative methods that could be used in enhanced weathering MRV.',
    title: 'Quantifying enhanced weathering',
    date: '09-11-2023',
  },
  {
    id: 'cdr-verification',
    logo: <CDRVerification />,
    color: 'secondary',
    summary:
      'Interactive tool for understanding Verification Confidence Levels (VCLs) for carbon removal.',
    title: 'CDR Verification Framework',
    date: '04-01-2024',
  },
  {
    id: 'forest-offsets-fires',
    logo: <ForestOffsetsFires />,
    color: 'red',
    summary:
      'Mapping forest carbon offset projects and their intersections with fires.',
    title: 'Offsets Fires',
    date: '06-25-2025',
  },
  {
    id: 'cmip6-downscaling',
    logo: <CMIP6Downscaling />,
    color: 'warm',
    summary: 'Interactive mapping tool for global downscaled climate data.',
    title: 'CMIP6 Downscaling',
    date: '06-30-2022',
  },
  {
    id: 'seaweed-farming',
    logo: <SeaweedFarming />,
    color: 'teal',
    summary: 'Mapping the costs and climate benefits of farming seaweed.',
    title: 'Seaweed Farming',
    date: '03-15-2022',
  },
  {
    id: 'cdr-database',
    logo: <CDRDatabase />,
    color: 'secondary',
    summary:
      'A database of reports on carbon dioxide removal project proposals.',
    title: 'CDR Database',
    date: '12-15-2021',
  },
  {
    id: 'permanence-calculator',
    logo: <PermanenceCalculator />,
    color: 'pink',
    summary: 'Comparing costs for temporary and permanent carbon removal.',
    title: 'Permanence Calculator',
    date: '12-09-2020',
  },
  {
    id: 'compliance-users',
    logo: <ComplianceUsers />,
    color: 'blue',
    summary: 'Tracking the users of compliance offsets.',
    title: 'Compliance users',
    date: '12-19-2024',
  },
  {
    id: 'soil-protocols',
    logo: <SoilProtocols />,
    color: 'orange',
    summary: 'A database of protocols used to credit soil carbon.',
    title: 'Soil Protocols',
    date: '10-13-2021',
  },
  {
    id: 'forest-offsets-crediting',
    logo: <ForestOffsetsCrediting />,
    color: 'green',
    summary:
      'Mapping our over-crediting analysis of forest carbon offset projects.',
    title: 'Offsets Crediting',
    date: '04-29-2021',
  },
  {
    id: 'forest-risks',
    logo: <ForestRisks />,
    color: 'red',
    summary: 'Mapping risks to forest carbon under a changing climate.',
    title: 'Forest Risks',
    date: '05-20-2021',
  },
  {
    id: 'forest-carbon',
    logo: <ForestCarbon />,
    color: 'green',
    summary: 'Mapping emissions related to forest carbon.',
    title: 'Forest Carbon',
    date: '09-21-2021',
  },
  {
    id: 'dac-calculator',
    logo: <DACCalculator />,
    color: 'purple',
    summary: 'Explore key parameters affecting the cost of direct air capture.',
    title: 'DAC Cost Calculator',
    date: '02-01-2021',
  },
]

export default tools
