const data = [
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 30.810810810810807,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.14,
    'short reference': 'Baek et al., 2023',
    link: 'https://doi.org/10.1029/2023EF003698',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 10.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 31.351351351351347,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.16,
    'short reference': 'Baek et al., 2023',
    link: 'https://doi.org/10.1029/2023EF003698',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 10.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 21.89189189189189,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.81,
    'short reference': 'Baek et al., 2023',
    link: 'https://doi.org/10.1029/2023EF003698',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 10.0,
    particle_diameter_um: 1220.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 22.43243243243243,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.83,
    'short reference': 'Baek et al., 2023',
    link: 'https://doi.org/10.1029/2023EF003698',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 10.0,
    particle_diameter_um: 1220.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.00016,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.0002,
    'short reference': 'Cipolla et al., 2021',
    link: 'https://doi.org/10.1016/j.advwatres.2021.103949',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.00344,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.0043,
    'short reference': 'Cipolla et al., 2021',
    link: 'https://doi.org/10.1016/j.advwatres.2021.103949',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.00704,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.0088,
    'short reference': 'Cipolla et al., 2021',
    link: 'https://doi.org/10.1016/j.advwatres.2021.103949',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.0033599999999999,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.0042,
    'short reference': 'Cipolla et al., 2022',
    link: 'https://doi.org/10.5194/bg-19-3877-2022',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.001768,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.00221,
    'short reference': 'Cipolla et al., 2022',
    link: 'https://doi.org/10.5194/bg-19-3877-2022',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.000496,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.00062,
    'short reference': 'Cipolla et al., 2022',
    link: 'https://doi.org/10.5194/bg-19-3877-2022',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.000312,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.00039,
    'short reference': 'Cipolla et al., 2022',
    link: 'https://doi.org/10.5194/bg-19-3877-2022',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 200.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 0.0648148148148148,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.035,
    'short reference': 'Chen et al., 2023',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.165766',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 180.0,
    particle_diameter_um: 214.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.0573192239858906,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.065,
    'short reference': 'Chen et al., 2023',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.165766',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 180.0,
    particle_diameter_um: 214.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.0124458874458874,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.023,
    'short reference': 'Amann et al., 2020',
    link: 'https://bg.copernicus.org/articles/17/103/2020/',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 220.0,
    particle_diameter_um: 1020.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.0265151515151515,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.049,
    'short reference': 'Amann et al., 2020',
    link: 'https://bg.copernicus.org/articles/17/103/2020/',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 220.0,
    particle_diameter_um: 43.5,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 35.61904761904762,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 3.74,
    'short reference': 'Kantola et al., 2023',
    link: 'https://doi.org/10.1111/gcb.16903',
    CDR_ineff_code_main: 'downstream',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 267.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 81.61904761904762,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 8.57,
    'short reference': 'Kantola et al., 2023',
    link: 'https://doi.org/10.1111/gcb.16903',
    CDR_ineff_code_main: 'downstream',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 267.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 4.666666666666667,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.56,
    'short reference': 'Lewis et al., 2021',
    link: 'https://doi.org/10.1016/j.apgeochem.2021.105023',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1531.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 2.4375,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.39,
    'short reference': 'Lewis et al., 2021',
    link: 'https://doi.org/10.1016/j.apgeochem.2021.105023',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1561.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 2.875,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.23,
    'short reference': 'Lewis et al., 2021',
    link: 'https://doi.org/10.1016/j.apgeochem.2021.105023',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 714.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 2.0,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.21,
    'short reference': 'Lewis et al., 2021',
    link: 'https://doi.org/10.1016/j.apgeochem.2021.105023',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 267.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 2.666666666666667,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.2,
    'short reference': 'Lewis et al., 2021',
    link: 'https://doi.org/10.1016/j.apgeochem.2021.105023',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1767.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 0.8571428571428572,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.09,
    'short reference': 'Lewis et al., 2021',
    link: 'https://doi.org/10.1016/j.apgeochem.2021.105023',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1138.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 25.047619047619047,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.63,
    'short reference': 'Beerling et al., 2024',
    link: 'https://doi.org/10.1073/pnas.2319436121',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 267.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 100.0,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 20.8,
    'short reference': 'Vienne et al., 2022',
    link: 'https://doi.org/10.3389/fclim.2022.869456',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 375.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 8.798076923076923,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.83,
    'short reference': 'Vienne et al., 2022',
    link: 'https://doi.org/10.3389/fclim.2022.869456',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 375.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 4.326923076923077,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.9,
    'short reference': 'Vienne et al., 2022',
    link: 'https://doi.org/10.3389/fclim.2022.869456',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 375.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.0065573770491803,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.002,
    'short reference': 'Buckingham and Henderson, 2024',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.167701',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.032,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.016,
    'short reference': 'Buckingham and Henderson, 2024',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.167701',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 0.0714285714285714,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.005,
    'short reference': 'Buckingham and Henderson, 2024',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.167701',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.0,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.0,
    'short reference': 'Buckingham and Henderson, 2024',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.167701',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.0588235294117647,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.02,
    'short reference': 'Buckingham and Henderson, 2024',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.167701',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.04,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.003,
    'short reference': 'Buckingham and Henderson, 2024',
    link: 'https://doi.org/10.1016/j.scitotenv.2023.167701',
    CDR_ineff_code_main: 'downstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 26.666666666666668,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.8,
    'short reference': 'Vanderkloot and Ryan, 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2023.105728',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 502.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 45.71428571428572,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.8,
    'short reference': 'Vanderkloot and Ryan, 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2023.105728',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 32.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 64.76190476190476,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 6.8,
    'short reference': 'Vanderkloot and Ryan, 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2023.105728',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 9.96,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 33.33333333333333,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.0,
    'short reference': 'Vanderkloot and Ryan, 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2023.105728',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 265.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 38.33333333333333,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.6,
    'short reference': 'Vanderkloot and Ryan, 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2023.105728',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 60.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 54.99999999999999,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 6.6,
    'short reference': 'Vanderkloot and Ryan, 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2023.105728',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 10.3,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'forsterite',
    CDR_efficiency_annual_percent: 82.85714285714285,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.87,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 86.41975308641973,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.7,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 63.33333333333333,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.57,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 62.22222222222222,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.56,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 57.777777777777786,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.52,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'forsterite',
    CDR_efficiency_annual_percent: 18.09523809523809,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.19,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 9.876543209876544,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.08,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'forsterite',
    CDR_efficiency_annual_percent: 0.9523809523809524,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.01,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.0,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.0,
    'short reference': 'Haque et al., 2023',
    link: 'https://doi.org/10.1021/acsearthspacechem.2c00374',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 100.0,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 14.5,
    'short reference': 'Khalidy et al., 2023',
    link: 'https://doi.org/10.1016/j.catena.2023.107524',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 375.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 47.172413793103445,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 6.84,
    'short reference': 'Khalidy et al., 2023',
    link: 'https://doi.org/10.1016/j.catena.2023.107524',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 375.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'forsterite',
    CDR_efficiency_annual_percent: 19.96527777777777,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 23.0,
    'short reference': 'Deng et al., 2023',
    link: 'https://doi.org/10.1038/s41598-023-36113-4',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 160.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'forsterite',
    CDR_efficiency_annual_percent: 0.0,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.0,
    'short reference': 'Deng et al., 2023',
    link: 'https://doi.org/10.1038/s41598-023-36113-4',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 160.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'forsterite',
    CDR_efficiency_annual_percent: 8.680555555555555,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 10.0,
    'short reference': 'Deng et al., 2023',
    link: 'https://doi.org/10.1038/s41598-023-36113-4',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 160.0,
    particle_diameter_um: null,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 1.2,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.015,
    'short reference': 'Vink and Knops, 2023',
    link: 'https://doi.org/10.3390/min13020235',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.0,
    particle_diameter_um: 900.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 4.965517241379311,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.44,
    'short reference': 'Guo et al., 2023',
    link: 'https://doi.org/10.1016/j.agsy.2023.103691',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 38.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 3.137931034482759,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.91,
    'short reference': 'Guo et al., 2023',
    link: 'https://doi.org/10.1016/j.agsy.2023.103691',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 38.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 1.944,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.243,
    'short reference': 'Dietzen and Rosing, 2023',
    link: 'https://doi.org/10.1016/j.ijggc.2023.103872',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 2.6,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.0,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.0,
    'short reference': 'Dietzen and Rosing, 2023',
    link: 'https://doi.org/10.1016/j.ijggc.2023.103872',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 10.0,
    particle_diameter_um: 2.6,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 1.993421708362404,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.0,
    'short reference': 'Pogge von Strandman et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.827698/full',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 127.0,
    particle_diameter_um: 125.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 12.957241104355626,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 13.0,
    'short reference': 'Pogge von Strandman et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.827698/full',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 127.0,
    particle_diameter_um: 125.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 1.8856341811993231,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 7.3,
    'short reference': 'Amann et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.929268/full',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 3226.0,
    particle_diameter_um: 43.5,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 10.531593583274722,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.96,
    'short reference': 'Amann et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.929268/full',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 2279.0,
    particle_diameter_um: 23.5,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'other',
    CDR_efficiency_annual_percent: 0.2079317495155515,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.19,
    'short reference': 'Amann et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.929268/full',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 3291.0,
    particle_diameter_um: 74.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.1017942657299759,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 3.13,
    'short reference': 'Amann et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.929268/full',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 3661.0,
    particle_diameter_um: 43.5,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 0.0864617773897847,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.9,
    'short reference': 'Amann et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.929268/full',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 3993.0,
    particle_diameter_um: 1020.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: -0.9333333333333336,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: -0.07,
    'short reference': 'Larkin et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.959229/full',
    CDR_ineff_code_main: 'local',
    count_group: 'river',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1767.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: -1.866666666666667,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: -0.14,
    'short reference': 'Larkin et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.959229/full',
    CDR_ineff_code_main: 'local',
    count_group: 'river',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1767.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 4.666666666666666,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.35,
    'short reference': 'Larkin et al., 2022',
    link: 'https://www.frontiersin.org/articles/10.3389/fclim.2022.959229/full',
    CDR_ineff_code_main: 'local',
    count_group: 'river',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 1767.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 2.9702970297029703,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.5,
    'short reference': 'Deltares field trials, 2022',
    link: 'https://publications.deltares.nl/11204378_000_0002.pdf',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.4,
    particle_diameter_um: 1500.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 3.564356435643565,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.8,
    'short reference': 'Deltares field trials, 2022',
    link: 'https://publications.deltares.nl/11204378_000_0002.pdf',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.4,
    particle_diameter_um: 1500.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 3.1683168316831685,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.6,
    'short reference': 'Deltares field trials, 2022',
    link: 'https://publications.deltares.nl/11204378_000_0002.pdf',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.4,
    particle_diameter_um: 1500.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 4.158415841584159,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.1,
    'short reference': 'Deltares field trials, 2022',
    link: 'https://publications.deltares.nl/11204378_000_0002.pdf',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.4,
    particle_diameter_um: 1500.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 3.1683168316831685,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.6,
    'short reference': 'Deltares field trials, 2022',
    link: 'https://publications.deltares.nl/11204378_000_0002.pdf',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.4,
    particle_diameter_um: 1500.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 4.158415841584159,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.1,
    'short reference': 'Deltares field trials, 2022',
    link: 'https://publications.deltares.nl/11204378_000_0002.pdf',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.4,
    particle_diameter_um: 1500.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 0.0728571428571428,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.0102,
    'short reference': 'Buckingham et al., 2022',
    link: 'https://doi.org/10.1016/j.apgeochem.2022.105482',
    CDR_ineff_code_main: 'downstream',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 187.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.6926987319144182,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 12.4,
    'short reference': 'Wood et al., 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2022.105511',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 1989.0,
    particle_diameter_um: 93.8,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.5642142897044857,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 10.1,
    'short reference': 'Wood et al., 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2022.105511',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 1989.0,
    particle_diameter_um: 93.8,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 19.457013574660635,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 38.7,
    'short reference': 'Wood et al., 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2022.105511',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 221.0,
    particle_diameter_um: 93.8,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 21.2166918049271,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 42.2,
    'short reference': 'Wood et al., 2023',
    link: 'https://doi.org/10.1016/j.apgeochem.2022.105511',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 221.0,
    particle_diameter_um: 93.8,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 0.5,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.14,
    'short reference': 'Rinder and von Hagke, 2021',
    link: 'https://doi.org/10.1016/j.jclepro.2021.128178',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 2.964285714285714,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.83,
    'short reference': 'Rinder and von Hagke, 2021',
    link: 'https://doi.org/10.1016/j.jclepro.2021.128178',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 10.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 3.928571428571429,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.1,
    'short reference': 'Rinder and von Hagke, 2021',
    link: 'https://doi.org/10.1016/j.jclepro.2021.128178',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 1.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 1.2272727272727273,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.08,
    'short reference': 'Rinder and von Hagke, 2021',
    link: 'https://doi.org/10.1016/j.jclepro.2021.128178',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 100.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 4.670454545454546,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.11,
    'short reference': 'Rinder and von Hagke, 2021',
    link: 'https://doi.org/10.1016/j.jclepro.2021.128178',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 10.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 8.045454545454547,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 7.08,
    'short reference': 'Rinder and von Hagke, 2021',
    link: 'https://doi.org/10.1016/j.jclepro.2021.128178',
    CDR_ineff_code_main: 'upstream',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 1.0,
  },
  {
    estimate_type: 'model',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 4.0,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.56,
    'short reference': 'Kelland et al., 2020',
    link: 'https://doi.org/10.1111/gcb.15089',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 1250.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 100.0,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.5952,
    'short reference': 'Haque et al., 2020a',
    link: 'https://doi.org/10.1016/j.ijggc.2020.103017',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.24,
    particle_diameter_um: 13.8,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 43.333333333333336,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.04,
    'short reference': 'Haque et al., 2020a',
    link: 'https://doi.org/10.1016/j.ijggc.2020.103017',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 5.0,
    particle_diameter_um: 8.2,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 47.5,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.57,
    'short reference': 'Haque et al., 2020a',
    link: 'https://doi.org/10.1016/j.ijggc.2020.103017',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 2.5,
    particle_diameter_um: 8.2,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 40.27777777777778,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.29,
    'short reference': 'Haque et al., 2020a',
    link: 'https://doi.org/10.1016/j.ijggc.2020.103017',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.5,
    particle_diameter_um: 8.2,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 5.833333333333333,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.84,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 30.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 4.500000000000001,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.16,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 6.5,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.68,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 150.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 7.625,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 7.32,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 200.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 6.666666666666667,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 9.6,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 300.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.75,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.44,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 400.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 7.5,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.08,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 30.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 5.5,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.64,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 5.5,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 3.96,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 150.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 4.375,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.2,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 200.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.0,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.0,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 30.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.0,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.0,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 100.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.6666666666666666,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.48,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 150.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.75,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.72,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 200.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.5833333333333333,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.84,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 300.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'wollastonite',
    CDR_efficiency_annual_percent: 0.1875,
    CDR_consistentWithZero: 'Y',
    CDRflux_tonsCO2_ha_yr: 0.36,
    'short reference': 'Haque et al., 2020b',
    link: 'https://doi.org/10.3389/fpls.2020.01012',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 400.0,
    particle_diameter_um: 63.7,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 100.0,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 6.9,
    'short reference': 'Dietzen et al., 2018',
    link: 'https://doi.org/10.1016/j.ijggc.2018.05.007',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 10.0,
    particle_diameter_um: 20.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 48.30917874396136,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 16.6,
    'short reference': 'Dietzen et al., 2018',
    link: 'https://doi.org/10.1016/j.ijggc.2018.05.007',
    CDR_ineff_code_main: 'none',
    count_group: 'soil',
    application_rate_ton_ha_yr: 49.8,
    particle_diameter_um: 20.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 24.028629856850717,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.47,
    'short reference': 'ten Berge et al., 2012',
    link: 'https://doi.org/10.1371/journal.pone.0042098',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 1.63,
    particle_diameter_um: 50.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 8.997955010224949,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.88,
    'short reference': 'ten Berge et al., 2012',
    link: 'https://doi.org/10.1371/journal.pone.0042098',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 8.15,
    particle_diameter_um: 50.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 3.378378378378378,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.65,
    'short reference': 'ten Berge et al., 2012',
    link: 'https://doi.org/10.1371/journal.pone.0042098',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 40.7,
    particle_diameter_um: 50.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'olivine or dunite',
    CDR_efficiency_annual_percent: 1.772875816993464,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 4.34,
    'short reference': 'ten Berge et al., 2012',
    link: 'https://doi.org/10.1371/journal.pone.0042098',
    CDR_ineff_code_main: 'local',
    count_group: 'soil',
    application_rate_ton_ha_yr: 204.0,
    particle_diameter_um: 50.0,
  },
  {
    estimate_type: 'field',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: null,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 0.62,
    'short reference': 'Linke et al., preprint',
    link: 'https://doi.org/10.21203/rs.3.rs-3439312/v1',
    CDR_ineff_code_main: 'local',
    count_group: 'export_deep',
    application_rate_ton_ha_yr: 6.5,
    particle_diameter_um: 36.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 28.369565217391308,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.61,
    'short reference': 'Reershemius et al., 2023',
    link: 'https://doi.org/10.1021/acs.est.3c03609',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 35.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 17.717391304347828,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.63,
    'short reference': 'Reershemius et al., 2023',
    link: 'https://doi.org/10.1021/acs.est.3c03609',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 35.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 31.086956521739133,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 2.86,
    'short reference': 'Reershemius et al., 2023',
    link: 'https://doi.org/10.1021/acs.est.3c03609',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 35.0,
  },
  {
    estimate_type: 'laboratory',
    feedstock_group: 'basalt',
    CDR_efficiency_annual_percent: 17.608695652173918,
    CDR_consistentWithZero: 'N',
    CDRflux_tonsCO2_ha_yr: 1.62,
    'short reference': 'Reershemius et al., 2023',
    link: 'https://doi.org/10.1021/acs.est.3c03609',
    CDR_ineff_code_main: 'local',
    count_group: 'export_shallow',
    application_rate_ton_ha_yr: 50.0,
    particle_diameter_um: 35.0,
  },
]
export default data
