const dacParameters = [
  {
    name: "Scale [tCO2/year]",
    displayName: "Scale",
    description: "An informative description of this parameter should go here.",
    unit: "tCO2/year",
    initValue: 1000000,
    validRange: [1, 10000000],
    step: 1,
    scale: "linear",
  },
  {
    name: "DAC Capacity Factor",
    displayName: "DAC Capacity Factor",
    description: "An informative description of this parameter should go here.",
    unit: "",
    initValue: 0.9,
    validRange: [0, 10],
    step: 1,
    scale: "linear",
  },
  {
    name: "DAC Section Lead Time [years]",
    displayName: "DAC Section Lead Time",
    description: "An informative description of this parameter should go here.",
    unit: "years",
    initValue: 3,
    validRange: [0, 10],
    step: 1,
    scale: "linear",
  },
  {
    name: "Total Capex [$]",
    displayName: "Capital Expenditure",
    description: "An informative description of this parameter should go here.",
    unit: "$",
    initValue: 936,
    validRange: [0, 1500],
    step: 1,
    scale: "linear",
  },
  {
    name: "Electric Power Requierement [MW]",
    displayName: "Electric Power Requierement",
    description: "An informative description of this parameter should go here.",
    unit: "MW",
    initValue: 46.6,
    validRange: [0, 100],
    step: 1,
    scale: "linear",
  },
  {
    name: "Thermal [GJ/tCO2]",
    displayName: "Thermal",
    description: "An informative description of this parameter should go here.",
    unit: "GJ/tCO2",
    initValue: 6.64,
    validRange: [0, 100],
    step: 1,
    scale: "linear",
  },
  {
    name: "Fixed O+M Costs [$/tCO2]",
    displayName: "Fixed O+M Costs",
    description: "An informative description of this parameter should go here.",
    unit: "$/tCO2",
    initValue: 34,
    validRange: [0, 100],
    step: 1,
    scale: "linear",
  },
  {
    name: "Varible O+M Cost [$/tCO2]",
    displayName: "Varible",
    description: "An informative description of this parameter should go here.",
    unit: "$/tCO2",
    initValue: 4,
    validRange: [0, 10],
    step: 1,
    scale: "linear",
  },
  {
    name: "Economic Lifetime [years]",
    displayName: "Economic Lifetime",
    description: "An informative description of this parameter should go here.",
    unit: "years",
    initValue: 20,
    validRange: [0, 50],
    step: 1,
    scale: "linear",
  },
  {
    name: "WACC [%]",
    displayName: "WACC",
    description: "An informative description of this parameter should go here.",
    unit: "%",
    initValue: 0.085,
    validRange: [0, 10],
    step: 1,
    scale: "linear",
  },
  {
    name: "Natural Gas Cost [$/mmBTU]",
    displayName: "Natural Gas Cost",
    description: "An informative description of this parameter should go here.",
    unit: "$/mmBTU",
    initValue: 3.43,
    validRange: [0, 10],
    step: 1,
    scale: "linear",
  }
]


export default dacParameters