const techData = {
  Wind: [
    {
      name: 'Overnight Cost [$/kW]',
      displayName: 'Overnight Cost',
      description:
        'The overnight cost refers to the cost of a construction project, without including interest incurred during construction.',
      unit: '$/kW',
      initValue: 1319.0,
      validRange: [500, 5000],
      step: 500,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Plant Size [MW]',
      unit: 'MW',
      initValue: 200.0,
      show: false,
    },
    {
      name: 'Lead Time [Years]',
      displayName: 'Lead Time',
      description:
        'The lead time describes the time between the beginning of construction and commissioning of the wind facility.',
      unit: 'Years',
      initValue: 3.0,
      validRange: [1, 10],
      step: 1,
      maxSteps: 10,
      scale: 'linear',
      width: 0.4,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Variable O&M [$/MWhr]',
      displayName: 'Variable O&M',
      description:
        'Variable operating and maintenance costs are the non-fuel portion of operating costs that are a function of the production (i.e. these are the costs associated with consumables that vary directly with the MWh production of the generating unit). An example of a Variable O&M cost is raw materials, such as water and chemicals, as well as other consumables.',
      unit: '$/MWhr',
      initValue: 0.0,
      validRange: [0, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Fixed O&M [$/kW-yr]',
      displayName: 'Fixed O&M',
      description:
        'Fixed operating and maintenance costs are associated with process that do not vary based on the production (i.e. MWh produced by a generating unit). An example of fixed O&M is lease payments and/or property taxes.',
      unit: '$/kW-yr',
      initValue: 26.22,
      validRange: [0, 100],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Availability',
      displayName: 'Availability',
      description:
        'The availability is the ratio of operating capacity of a given generating resource by the maximum operating capacity over the course of a single day. For wind, this is analogous to the number of hours in a day that the wind is blowing divided by 24 hours.',
      unit: '',
      initValue: 0.52,
      validRange: [0.05, 0.6],
      step: 0.01,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Scaling Factor',
      displayName: 'Scaling Factor',
      description:
        'The scaling factor is an exponent that relates a known value (X1) at a given capacity (Capacity1) to a new value (X2) at a different, specified capacity (Capacity2). The relationship is: X2 = X1*(Capacity2/Capacity1)^(Scaling Factor).',
      unit: '',
      initValue: 0.95,
      validRange: [0.5, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
  ],
  'Advanced NGCC': [
    {
      name: 'Overnight Cost [$/kW]',
      displayName: 'Overnight Cost',
      description:
        'The overnight cost refers to the cost of a construction project, without including interest incurred during construction.',
      unit: '$/kW',
      initValue: 954.0,
      validRange: [500, 5000],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Plant Size [MW]',
      unit: 'MW',
      initValue: 1083.0,
      show: false,
    },
    {
      name: 'Lead Time [Years]',
      displayName: 'Lead Time',
      description:
        'The lead time describes the time between the beginning of construction and commissioning of the advanced NGCC facility.',
      unit: 'Years',
      initValue: 3.0,
      validRange: [1, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Variable O&M [$/MWhr]',
      displayName: 'Variable O&M',
      description:
        'Variable operating and maintenance costs are the non-fuel portion of operating costs that are a function of the production (i.e. these are the costs associated with consumables that vary directly with the MWh production of the generating unit). An example of a Variable O&M cost is raw materials, such as water and chemicals, as well as other consumables.',
      unit: '$/MWhr',
      initValue: 1.86,
      validRange: [0, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Fixed O&M [$/kW-yr]',
      displayName: 'Fixed O&M',
      description:
        'Fixed operating and maintenance costs are associated with process that do not vary based on the production (i.e. MWh produced by a generating unit). An example of fixed O&M is lease payments and/or property taxes.',
      unit: '$/kW-yr',
      initValue: 12.15,
      validRange: [0, 100],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Final Heat Rate [BTU/kWh]',
      displayName: 'Final Heat Rate',
      description:
        'The heat rate is the amount of energy used by an electrical generator/power plant to generate one kilowatthour (kWh) of electricity (EIA: https://www.eia.gov/tools/faqs/faq.php?id=107&t=3)',
      unit: 'BTU/kWh',
      initValue: 6370.0,
      validRange: [1000, 15000],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Availability',
      displayName: 'Availability',
      description:
        'The availability is the ratio of operating capacity of a given generating resource by the maximum operating capacity over the course of a single day. For NGCC, this is typically near 100% as NGCC is a dispatchable energy resource.',
      unit: '',
      initValue: 1.0,
      validRange: [0.7, 1],
      step: 0.01,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Scaling Factor',
      displayName: 'Scaling Factor',
      description:
        'The scaling factor is an exponent that relates a known value (X1) at a given capacity (Capacity1) to a new value (X2) at a different, specified capacity (Capacity2). The relationship is: X2 = X1*(Capacity2/Capacity1)^(Scaling Factor).',
      unit: '',
      initValue: 0.7,
      validRange: [0.5, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Total CO2 eq [lb/mmbtu]',
      displayName: 'Total CO₂eq',
      description:
        'The total CO₂eq refers to the total emissions of CO2 directly from the energy generating source.',
      unit: 'lb/mmbtu',
      initValue: 119,
      validRange: [0, 200],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
  ],
  'NGCC w/ CCS': [
    {
      name: 'Overnight Cost [$/kW]',
      displayName: 'Overnight Cost',
      description:
        'The overnight cost refers to the cost of a construction project, without including interest incurred during construction.',
      unit: '$/kW',
      initValue: 2569.0,
      validRange: [500, 5000],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Plant Size [MW]',
      unit: 'MW',
      initValue: 377.0,
      validRange: [100, 2500],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: false,
    },
    {
      name: 'Lead Time [Years]',
      displayName: 'Lead Time',
      description:
        'The lead time describes the time between the beginning of construction and commissioning of the NGCC with CCS facility.',
      unit: 'Years',
      initValue: 3.0,
      validRange: [1, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Variable O&M [$/MWhr]',
      displayName: 'Variable O&M',
      description:
        'Variable operating and maintenance costs are the non-fuel portion of operating costs that are a function of the production (i.e. these are the costs associated with consumables that vary directly with the MWh production of the generating unit). An example of a Variable O&M cost is raw materials, such as water and chemicals, as well as other consumables.',
      unit: '$/MWhr',
      initValue: 5.82,
      validRange: [0, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Fixed O&M [$/kW-yr]',
      displayName: 'Fixed O&M',
      description:
        'Fixed operating and maintenance costs are associated with process that do not vary based on the production (i.e. MWh produced by a generating unit). An example of fixed O&M is lease payments and/or property taxes.',
      unit: '$/kW-yr',
      initValue: 27.48,
      validRange: [0, 100],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Final Heat Rate [BTU/kWh]',
      displayName: 'Final Heat Rate',
      description:
        'The heat rate is the amount of energy used by an electrical generator/power plant to generate one kilowatthour (kWh) of electricity (EIA: https://www.eia.gov/tools/faqs/faq.php?id=107&t=3)',
      unit: 'BTU/kWh',
      initValue: 7124.0,
      validRange: [1000, 15000],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Availability',
      displayName: 'Availability',
      description:
        'The availability is the ratio of operating capacity of a given generating resource by the maximum operating capacity over the course of a single day. For NGCC with CCS, this is typically near 100% as NGCC is a dispatchable energy resource.',
      unit: '',
      initValue: 1.0,
      validRange: [0.7, 1],
      step: 0.01,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Scaling Factor',
      displayName: 'Scaling Factor',
      description:
        'The scaling factor is an exponent that relates a known value (X1) at a given capacity (Capacity1) to a new value (X2) at a different, specified capacity (Capacity2). The relationship is: X2 = X1*(Capacity2/Capacity1)^(Scaling Factor). ',
      unit: '',
      initValue: 0.7,
      validRange: [0.5, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Capture Efficiency',
      displayName: 'Capture Efficiency',
      description:
        'Capture efficiency refers to the fraction of CO2 produced from the NGCC generation process that is captured via carbon capture and storage.',
      unit: '',
      initValue: 0.9,
      validRange: [0, 0.99],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Total CO2 eq [lb/mmbtu]',
      displayName: 'Total CO₂eq',
      description:
        'The total CO₂eq refers to the total emissions of CO2 directly from the energy generating source.',
      unit: 'lb/mmbtu',
      initValue: 119,
      validRange: [0, 200],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
  ],
  Solar: [
    {
      name: 'Overnight Cost [$/kW]',
      displayName: 'Overnight Cost',
      description:
        'The overnight cost refers to the cost of a construction project, without including interest incurred during construction.',
      unit: '$/kW',
      initValue: 1331.0,
      validRange: [500, 5000],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Plant Size [MW]',
      unit: 'MW',
      initValue: 150.0,
      show: false,
    },
    {
      name: 'Lead Time [Years]',
      displayName: 'Lead Time',
      description:
        'The lead time describes the time between the beginning of construction and commissioning of the solar facility.',
      unit: 'Years',
      initValue: 2.0,
      validRange: [1, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Variable O&M [$/MWhr]',
      displayName: 'Variable O&M',
      description:
        'Variable operating and maintenance costs are the non-fuel portion of operating costs that are a function of the production (i.e. these are the costs associated with consumables that vary directly with the MWh production of the generating unit). An example of a Variable O&M cost is raw materials, such as water and chemicals, as well as other consumables.',
      unit: '$/MWhr',
      initValue: 0.0,
      validRange: [0, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Fixed O&M [$/kW-yr]',
      displayName: 'Fixed O&M',
      description:
        'Fixed operating and maintenance costs are associated with process that do not vary based on the production (i.e. MWh produced by a generating unit). An example of fixed O&M is lease payments and/or property taxes.',
      unit: '$/kW-yr',
      initValue: 15.19,
      validRange: [0, 100],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Availability',
      displayName: 'Availability',
      description:
        'The availability is the ratio of operating capacity of a given generating resource by the maximum operating capacity over the course of a single day. For solar, this is equivalent to the number of sunlight hours in a day divided by 24 hours.',
      unit: '',
      initValue: 0.352,
      validRange: [0.05, 0.45],
      step: 0.01,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Scaling Factor',
      displayName: 'Scaling Factor',
      description:
        'The scaling factor is an exponent that relates a known value (X1) at a given capacity (Capacity1) to a new value (X2) at a different, specified capacity (Capacity2). The relationship is: X2 = X1*(Capacity2/Capacity1)^(Scaling Factor). ',
      unit: '',
      initValue: 0.95,
      validRange: [0.5, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Capture Efficiency',
      displayName: 'Capture Efficiency',
      unit: '',
      initValue: 0.0,
      validRange: [0, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: false,
    },
  ],
  'Battery Storage': [
    {
      name: 'Overnight Cost [$/kW]',
      displayName: 'Overnight Cost',
      description:
        'The overnight cost refers to the cost of a construction project, without including interest incurred during construction.',
      unit: '$/kW',
      initValue: 1383.0,
      validRange: [100, 5000],
      step: 100,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Plant Size [MW]',
      unit: 'MW',
      initValue: 50.0,
      show: false,
    },
    {
      name: 'Battery Capacity [MWhr]',
      displayName: 'Battery Capacity',
      description:
        'The battery capacity represents the maximum amount of energy that can be stored in a single battery. This is measured in MWh, which represents the voltage the battery provides multiplied by how much current the battery can provide for a given number of hours.',
      unit: 'MWhr',
      initValue: 200.0,
      validRange: [50, 500],
      step: 10,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Lead Time [Years]',
      displayName: 'Lead Time',
      description:
        'The lead time describes the time between the beginning of construction and commissioning of the battery storage facility.',
      unit: 'Years',
      initValue: 1.0,
      validRange: [1, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Variable O&M [$/MWhr]',
      displayName: 'Variable O&M',
      description:
        'Variable operating and maintenance costs are the non-fuel portion of operating costs that are a function of the production (i.e. these are the costs associated with consumables that vary directly with the MWh production of the generating unit). An example of a Variable O&M cost is raw materials, such as water and chemicals, as well as other consumables.',
      unit: '$/MWhr',
      initValue: 0.0,
      validRange: [0, 10],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Fixed O&M [$/kW-yr]',
      displayName: 'Fixed O&M',
      description:
        'Fixed operating and maintenance costs are associated with process that do not vary based on the production (i.e. MWh stored by the batteries). An example of fixed O&M is lease payments and/or property taxes.',
      unit: '$/kW-yr',
      initValue: 24.7,
      validRange: [0, 100],
      step: 1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Efficiency (Thermal or Round Trip)',
      displayName: 'Efficiency (Round Trip)',
      description:
        'The round trip battery efficiency is the ratio of the amount of energy retrievable from storage to the amount of energy put into stroage.',
      unit: '',
      initValue: 0.85,
      validRange: [0.6, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
    {
      name: 'Scaling Factor',
      displayName: 'Scaling Factor',
      description:
        'The scaling factor is an exponent that relates a known value (X1) at a given capacity (Capacity1) to a new value (X2) at a different, specified capacity (Capacity2). The relationship is: X2 = X1*(Capacity2/Capacity1)^(Scaling Factor).',
      unit: '',
      initValue: 0.95,
      validRange: [0.5, 1],
      step: 0.1,
      scale: 'linear',
      width: 0.8,
      chartHeight: 160,
      show: true,
    },
  ],
}

export default techData
